### PR TITLE
OVC5 Carrier Firmware

### PR DESCRIPTION
**Pull request by gbalke**
This builds off of @luca-della-vedova's branch but the changes are large enough that I'd like to merge directly to master. With these adjustments, we can see that images are making it through!
image

I'm going to continue building off of this for 4-lane MIPI testing.

# Feature additions
* GPIO driver via sysfs
* Triggering via GPIO
* Per-camera udmabufs
* Camera identifier independent from vdma identifier in config file
* USB Ethernet automatically starts on USB connection (`/etc/network/interfaces` corrections)
* Select which camera is used to trigger the readout from the camera buffers via gpio
* Ctrl-C works better at escaping
* Cameras are enabled at start of program and disabled at the end

There are likely a number of other features that I forgot... These are the important ones!

### CODE REVIEW

**Comment by luca-della-vedova** [comment]
Thanks for the work on the carrier! I finally had a chance to try this out and will throw feedback scattered here:

First of all, I didn't know you can do that grouping of blocks in Vivado, it's super neat and so much more readable!

As soon as I opened the design I was greeted by a few errors about mapping of pins to one of the MIPI blocks (specifically cam3)
image. The errors caused the cam3 block to fail configuration and it reset to default (i.e. having the AXI interface for configuration, being 2 lane and RAW8).

I'm also a bit worried about the GPIO triggering from Linux, while it is great for prototyping I think we might want to run the trigger in FPGA to make sure it runs at fixed intervals and is not affected by jitter due to process scheduling or CPU load. There is an IP for this (`trigger_timer`) and a timer_driver in the code that should help make it somewhat easier to configure for arbitrary frequencies and duty cycles.

Can you give a try at removing the C source files under `hw-description` from version control and see if anything :boom: ? I suspect they are autogenerated and we can get away with taking them off.

I'm also unable to get this to boot but it might be some other issue, I'll try to give more detailed feedback when I manage to do it

**Comment by gbalke** [comment]
Looks like I accidentally cleared the settings for cam3. I'm fixing that up.

**Comment by luca-della-vedova** [comment]
It boots! :tada: it proves that there is something off with my setup :sweat_smile: 
I noticed that there is only one USB Ethernet interface up. Since you are touching networking in this PR I think it would be good to at least get both of them up and assign address through DHCP to the host computer, we can then add support for streaming images in parallel through the two USB interfaces (probably followup PR since that requires some work in the drivers).

**Comment by gbalke** [comment]
Finally got the USB ethernet working! This is the output of `lsusb -t` on my machine:
```
|__ Port 3: Dev 15, If 0, Class=Communications, Driver=cdc_ether, 480M
|__ Port 3: Dev 15, If 1, Class=CDC Data, Driver=cdc_ether, 480M      
|__ Port 4: Dev 16, If 1, Class=CDC Data, Driver=cdc_ether, 480M      
|__ Port 4: Dev 16, If 0, Class=Communications, Driver=cdc_ether, 480M
```
`ifconfig` on the host side:
```
enx96d4cf8bda12: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500    
        inet 10.0.1.2  netmask 255.0.0.0  broadcast 10.255.255.255       
        inet6 fe80::3b3c:c922:522a:4ea5  prefixlen 64  scopeid 0x20<link>
        ether 96:d4:cf:8b:da:12  txqueuelen 1000  (Ethernet)             
        RX packets 37  bytes 4408 (4.4 KB)                               
        RX errors 0  dropped 0  overruns 0  frame 0                      
        TX packets 247  bytes 39030 (39.0 KB)                            
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0       
                                                                         
enxea564a3644a9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500    
        inet 10.0.2.2  netmask 255.0.0.0  broadcast 10.255.255.255       
        inet6 fe80::de12:29ca:d8ba:b5b5  prefixlen 64  scopeid 0x20<link>
        ether ea:56:4a:36:44:a9  txqueuelen 1000  (Ethernet)             
        RX packets 33  bytes 3601 (3.6 KB)                               
        RX errors 0  dropped 0  overruns 0  frame 0                      
        TX packets 111  bytes 17435 (17.4 KB)                            
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0       
```
`ifconfig` on the device side:
```
usb0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.1  netmask 255.255.255.252  broadcast 10.0.1.3
        inet6 fe80::7480:e1ff:fe07:3f36  prefixlen 64  scopeid 0x20<link>
        ether 76:80:e1:07:3f:36  txqueuelen 1000  (Ethernet)
        RX packets 252  bytes 36336 (35.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 37  bytes 4926 (4.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.1  netmask 255.255.255.252  broadcast 10.0.2.3
        inet6 fe80::8b7:b9ff:fecd:6860  prefixlen 64  scopeid 0x20<link>
        ether 0a:b7:b9:cd:68:60  txqueuelen 1000  (Ethernet)
        RX packets 111  bytes 15881 (15.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34  bytes 4133 (4.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Ping to each address from host:
```
PING 10.0.1.1 (10.0.1.1) 56(84) bytes of data.        
64 bytes from 10.0.1.1: icmp_seq=1 ttl=64 time=5.12 ms
64 bytes from 10.0.1.1: icmp_seq=2 ttl=64 time=3.87 ms
64 bytes from 10.0.1.1: icmp_seq=3 ttl=64 time=1.83 ms

PING 10.0.2.1 (10.0.2.1) 56(84) bytes of data.         
64 bytes from 10.0.2.1: icmp_seq=1 ttl=64 time=2.51 ms 
64 bytes from 10.0.2.1: icmp_seq=2 ttl=64 time=0.810 ms
64 bytes from 10.0.2.1: icmp_seq=3 ttl=64 time=3.05 ms 
```

**Comment by gbalke** [comment]
I just added in some script files that will end up in the home directory. All you have to do at startup is run:
```
~/ethernet_utils/init_files/distribute_files
systemctl enable usb-gadget.service
systemctl start usb-gadget.service
```
This will register with `systemd` so it will launch at startup every time without any future input. I'll make this part of the automagic provisioning script in a follow-up PR.

**Review by luca-della-vedova — APPROVED** [review]
Great, thanks for iterating on this!

**Pull request merged**
