### PR TITLE
Add kicad project for OVC5

### PR DESCRIPTION
**Pull request by luca-della-vedova**
OVC5 will be a carrier board for an Enclustra Mercury XU5 Zynq Ultrascale+ SoM.

Still TODO:

- [x] Check VBUS line on the Cypress hub and see if we can short it to 3.3V.
- [x] Check and route miscellaneous GPIO from the Enclustra module (including VCC_CFG_MIO, boot pins to DIP)
- [x] Add 100mil GPIO headers and general GPIO (i.e Stemma QWIIC)
- [x] Address all the TODOs in the schematic
- [x] Length and skew tuning for all the differential lines, taking into account net lengths on the SoM for MIPI clock - data lanes skew
- [x] Figure out whether we need ground pours on top / bottom layers for the USB SS lines (recommended on [Cypress](https://www.cypress.com/file/410976/download) guidelines but not on [Microchip's](http://ww1.microchip.com/downloads/en/Appnotes/AN26.2-Application-Note-DS00001876C.pdf)
- [x] Figure out if it's a good idea to add the RC filter + ground plane to the connector shields

### CODE REVIEW

**Comment by gbalke** [comment]
Is U13 meant to be used for a future build? I don't see any current use for it other than some sort of isolation? This is a multiplexer so I'd expect a second device connection.
image

**Comment by gbalke** [comment]
For U9, the 1.2V output is coming from a switching regulator. Below a certain voltage is it okay to directly supply logic voltage off a switching regulator? I'm used to buffering it through an LDO.

**Comment by gbalke** [comment]
For the Enclustra module, 
image

It appears we should use terminating resistors on the base board for all diff pairs?

**Comment by luca-della-vedova** [comment]
They seem to be referring to HD pins, all the differential pairs go to HP pins (B65 and B66 are HP pins) and I think these should have internal termination

**Comment by gbalke** [comment]
__Nit__: Missing the suggested ferrite bead
image

**Comment by gbalke** [comment]
More nit: could you ad some space between the crystal's identifier and the value? I accidentally read that as 125MHz for the longest time :laughing: 

image

**Comment by luca-della-vedova** [comment]
Thanks for the feedback!
> Nit: Missing the suggested ferrite bead

Yea this was a tough call, I couldn't come with a nice way to split the power planes and add the bead in-between, if you find a possible way let me know!

> Also pins 2 and 4 appear to be grounded in the reference (plus a resistor)?
I didn't notice and went into autopilot mode when adding the crystal, done good find!

**Comment by gbalke** [comment]
Some commentary from the guide again:
image
Based on this, VBUS should have 4x 22nF caps:
image
Additionally, these caps should be isolated via a ferrite bead: 
image

**Comment by gbalke** [comment]
PGANG should be pulled low via a 100k and PSELF pulled up with a 10k.
image
image

**Comment by luca-della-vedova** [comment]
> Based on this, VBUS should have 4x 22nF caps (I noticed this as a TODO):

They mention the 4x 22n capacitors for applications with a PD controller since it will act as a regulator, the issue is we don't use a controller in this design so that specific guideline is not really applicable.
I went for going closer to the USB specification. It allows a maximum of 10uF at the device node with additional capacitance being allowed if it's after a load switch which can limit the current inrush.
The capacitance on the bus itself is effectively 0, after the load switch there is (at least) 2x 22uF capacitors (VMOD of the Enclustra module) but there is a soft start in the TPS2121 to make the current manageable.
I'm open to adding some capacitance straight into the raw VBUS line, I have been a bit more conservative so far because there is a lot of capacitance downstream of the multiplexer and didn't want to risk it.

> Additionally, these caps should be isolated via a ferrite bead:

I couldn't find any mention in the datasheet of [TPS2561](https://www.ti.com/lit/ds/symlink/tps2561.pdf?ts=1616556872194&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FTPS2561)? I guess it's a generic USB VBUS guideline?

> I'd also recommend using this filter circuit to isolate the shield from ground. I don't think a direct connection is a good idea as the shield is expected to pick up noise (and we don't want that being used for reference voltage).

Yea this is the big one that I was conflicted about, my main worry was whether to:
* Connect all the pins in the shield together (which means we will have a ground plane which is not exactly ground, going against all the differential pair routing guidelines that say you shouldn't have plane discontinuities below the signals.
* Only connect one pin in a corner, probably not as clean but at least the ground discontinuity is only in one point?
* Do nothing

I guess option 2 might be the easiest?

> PGANG should be pulled low via a 100k and PSELF pulled up with a 10k.

This, together with CHIPEN, is a mix of laziness and general toughness to place and route a lot of components in such a high density footprint. I tried to skim all the components that seem "not necessary". I can't figure out what the difference would be between a pullup / pulldown resistor or directly connecting the pins to 3v3 / ground since they seem to be normal inputs. If they are normal inputs I can only think of two cases in which it would make sense:
* The pins being pulled high are in a different voltage rail and the resistor actually was used to limit current but that sounds a bit unlikely.
* We wanted the flexibility to attach them to some switch / pin header that shorts them to the opposite rail, but we don't really want to do this.

What do you think?

**Comment by gbalke** [comment]
>They mention the 4x 22n capacitors for applications with a PD controller since it will act as a regulator, the issue is we don't use a controller in this design so that specific guideline is not really applicable.
I went for going closer to the USB specification. It allows a maximum of 10uF at the device node with additional capacitance being allowed if it's after a load switch which can limit the current inrush.
The capacitance on the bus itself is effectively 0, after the load switch there is (at least) 2x 22uF capacitors (VMOD of the Enclustra module) but there is a soft start in the TPS2121 to make the current manageable.
I'm open to adding some capacitance straight into the raw VBUS line, I have been a bit more conservative so far because there is a lot of capacitance downstream of the multiplexer and didn't want to risk it.

Maybe just add one of the 22nF? I'd prefer a little bit of capacitance just to be safe.

> I couldn't find any mention in the datasheet of TPS2561? I guess it's a generic USB VBUS guideline?

I don't see any specific design for USB on this datasheet. It also recommends 2x 15uF caps on the outputs. I also read the beginning of section 2.13 and it says we should be using at least 120 uF (based on the USB spec) so these 100uF caps don't look to be enough.

> Yea this is the big one that I was conflicted about, my main worry was whether to:
> * Connect all the pins in the shield together (which means we will have a ground plane which is not exactly ground, going against all the differential pair routing guidelines that say you shouldn't have plane discontinuities below the signals.
> * Only connect one pin in a corner, probably not as clean but at least the ground discontinuity is only in one point?
> * Do nothing
I guess option 2 might be the easiest?

I took a look at https://www.ti.com/sc/docs/apps/msp/intrface/usb/emitest.pdf and it seems to just suggest connecting the shielding to ground far away from signal. Also based on [this discussion](https://electronics.stackexchange.com/questions/4515/how-to-connect-usb-connector-shield), it seems reasonable to just connect straight to ground. However, it seems like Cypress is pretty consistent with their suggestion so it might be best to just trust them as we are using their chip? I feel like ignoring the spec always leads to unforeseen consequences :cry:.

>This, together with CHIPEN, is a mix of laziness and general toughness to place and route a lot of components in such a high density footprint. I tried to skim all the components that seem "not necessary". I can't figure out what the difference would be between a pullup / pulldown resistor or directly connecting the pins to 3v3 / ground since they seem to be normal inputs. If they are normal inputs I can only think of two cases in which it would make sense:
> * The pins being pulled high are in a different voltage rail and the resistor actually was used to limit current but that sounds a bit unlikely.
> * We wanted the flexibility to attach them to some switch / pin header that shorts them to the opposite rail, but we don't really want to do this.
What do you think?

Similar to above: I don't want to diverge from the spec too much just because it seems like we can. We don't know what's going on and a high value pull-up likely has a reason behind it. This IC is immensely complicated and I don't think we want to have it fall through because of a couple missing passives :disappointed:. I'd be happy to try and fit them in tomorrow.

**Comment by luca-della-vedova** [comment]
> Maybe just add one of the 22nF? I'd prefer a little bit of capacitance just to be safe.

I added a 100nF, we don't have any 22nF and it's probably not worth it to add a new item to the BOM just for one capacitor.

> I don't see any specific design for USB on this datasheet. It also recommends 2x 15uF caps on the outputs. I also read the beginning of section 2.13 and it says we should be using at least 120 uF (based on the USB spec) so these 100uF caps don't look to be enough.

I'm not sure I understand what you mean by 2x 15uF on the outputs? Anyway the reason I put 100uF was because they were the largest that could be easily supplied in a ceramic form factor, larger capacitors are usually electrolytic.
There doesn't seem to be a lack of space on that side of the PCB so changed them to 150uF electrolytic (similar to what they do on their development kit). I also added a series ferrite bead since it seems to be a pretty common setup for USB VBUS lines.

> I took a look at https://www.ti.com/sc/docs/apps/msp/intrface/usb/emitest.pdf and it seems to just suggest connecting the shielding to ground far away from signal. Also based on [this discussion](https://electronics.stackexchange.com/questions/4515/how-to-connect-usb-connector-shield), it seems reasonable to just connect straight to ground. However, it seems like Cypress is pretty consistent with their suggestion so it might be best to just trust them as we are using their chip? I feel like ignoring the spec always leads to unforeseen consequences cry.

OK I added a solid plane on the top layer connected to the shield, together with the parallel RC circuit, on both USB connectors. Does that look reasonable?

> Similar to above: I don't want to diverge from the spec too much just because it seems like we can. We don't know what's going on and a high value pull-up likely has a reason behind it. This IC is immensely complicated and I don't think we want to have it fall through because of a couple missing passives disappointed. I'd be happy to try and fit them in tomorrow.

Yea that part of the PCB is a nightmare, I'll be leaving it first but feel free to give it a shot (together with the ferrite in the 3v3 lines).

I also added ground vias next to the layer transition of the SS lines, as well as 2mm spaced via stitching around the perimeter of the PCB, where possible (the bottom of the PCB is very crowded and there is no space and I'm not 100% sure it's a good idea to have it done under the USB connectors since they are in a separate ground and if the via was to touch the shield it would short it).

I'm tempted to skip the ground pour on top / bottom layer for the USB3 lanes they recommend (refer to first post). From what I understand it is only effective if there are a lot of vias to make sure it is properly grounded (otherwise it might even be counter-productive) and we already have a lot of stuff going on in those layers that might make it hard to have proper grounding.
They can get away with it in the reference design since they have all the traces on one side and they are very nicely spaced / very long, but that is not quite the case for this board.

**Review by gbalke — APPROVED** [review]

**Comment by luca-della-vedova** [comment]
Gerbers added and board sent for fabrication

**Pull request merged**
